version: '3'

services:
  db:
    container_name: ordering_db
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ordering_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data2